### ISSUE TITLE
Mac packages are a ZIP within a ZIP

### ISSUE THREAD

**Issue by suy** [alex-spataru/QtApp-Template#2]
Hola Alex. 👋🏼 😃 

Thank you for the template. It has helped me a lot on setting up my project, and I will probably need to look at it again for a Windows package.

I would like to mention that the ZIP packages coming straight from the Github workflows are a ZIP... which inside the run was content already in another ZIP. For example, if I [go the latest run](https://github.com/alex-spataru/QtApp-Template/actions/runs/1659325545), the macOS.zip download is a ZIP package, which in turn contains the ZIP that was created via the workflow.

[Seems there is no solution to this](https://github.com/actions/upload-artifact#zipped-artifact-downloads), but I'd like to point it out just in case you want to skip the zipping, to avoid confusion. Myself, I've went the way to upload the whole `.app` bundle, as the upload-artifact action can upload a directory just fine, but also to create a DMG with `macdeployqt` and publish that as well. DMGs used to be the way to get applications on Macs, at least some time ago, so I suppose that will be good.

For reference, here is what I've used in my case:

```yaml
      - name: Deploy app
        run: |
          macdeployqt bin/MyApp.app
          macdeployqt bin/MyApp.app -dmg
          mv bin/MyApp.app MyApp-${{env.APP_VERSION}}.app
          mv bin/MyApp.dmg MyApp-${{env.APP_VERSION}}.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-${{env.APP_VERSION}}.dmg
          path: MyApp-${{env.APP_VERSION}}.dmg

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-${{env.APP_VERSION}}.app
          path: MyApp-${{env.APP_VERSION}}.app

```

Cheers, and thank you again.
